# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Aaron A. Meek
email: aaronameek@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome! My name is Aaron Meek, and I am a political science Ph.D. student at The George
  Washington University in Washington, DC. My research centers on American judicial politics,
  and some of my current projects include work on administrative agency compliance with
  federal court of appeals decisions, the impact of state supreme court selection systems
  on legal opinion clarity, and the influence of congressional court curbing on the behavior
  of Supreme Court justices. I am originally from Rochester Hills, MI, and received my B.A.
  in political science from Michigan State University and my M.A. in political science from
  The George Washington University. Outside of academic work, I enjoy spending my time at the
  piano, watching Spartan football, and hanging out with my nieces and nephews.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: Aaa
github_username:  aaronameek

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
